import enum

import pygame

from field import Field
from deck import Deck


# перечисление "константы окна игры".
class WindowParameters(enum.IntEnum):
    CELL_SIZE = 30

    HALF_OF_CELL_SIZE = CELL_SIZE // 2

    CELL_BORDER_SIZE = 1

    BACKGROUND_FILL_CHIP_BORDER_SIZE = HALF_OF_CELL_SIZE

    CURRENT_CHIP_BORDER_SIZE = 3

    FONT_SIZE = int(CELL_SIZE / 2.4)

    DISPLAYED_PART_OF_FIELD_WIDTH = \
        (CELL_SIZE *
         Field.DISPLAYED_PART_N_CELLS_IN_WIDTH)

    DISPLAYED_PART_OF_FIELD_HEIGHT = \
        (CELL_SIZE *
         Field.DISPLAYED_PART_N_CELLS_IN_HEIGHT)

    DISPLAYED_PART_OF_FIELD_MIN_X = \
        HALF_OF_CELL_SIZE

    DISPLAYED_PART_OF_FIELD_MIN_Y = \
        DISPLAYED_PART_OF_FIELD_MIN_X

    DISPLAYED_PART_OF_FIELD_MAX_X = \
        (DISPLAYED_PART_OF_FIELD_MIN_X +
         DISPLAYED_PART_OF_FIELD_WIDTH)

    DISPLAYED_PART_OF_FIELD_MAX_Y = \
        (DISPLAYED_PART_OF_FIELD_MIN_Y +
         DISPLAYED_PART_OF_FIELD_HEIGHT)

    LOWER_PANEL_HEIGHT = 3 * CELL_SIZE

    DECK_MIN_X = HALF_OF_CELL_SIZE

    DECK_MIN_Y = \
        (DISPLAYED_PART_OF_FIELD_HEIGHT +
         2 * HALF_OF_CELL_SIZE)

    DECK_DISTANCE_BETWEEN_CHIPS = CELL_SIZE // 5

    DECK_WIDTH = \
        (Deck.N_CHIPS_MAX_VALUE * CELL_SIZE +
         (Deck.N_CHIPS_MAX_VALUE - 1) * DECK_DISTANCE_BETWEEN_CHIPS)

    DECK_MAX_X = DECK_MIN_X + DECK_WIDTH

    DECK_HEIGHT = CELL_SIZE

    DECK_STEP = CELL_SIZE + DECK_DISTANCE_BETWEEN_CHIPS

    N_BUTTONS = 3

    BUTTONS_MIN_X = DECK_MAX_X + CELL_SIZE

    BUTTONS_MIN_Y = DECK_MIN_Y

    BUTTON_WIDTH = CELL_SIZE * 2.2

    DISTANCE_BETWEEN_BUTTONS = DECK_DISTANCE_BETWEEN_CHIPS

    BUTTONS_WIDTH = \
        (N_BUTTONS * BUTTON_WIDTH + (N_BUTTONS - 1) * DISTANCE_BETWEEN_BUTTONS)

    BUTTONS_MAX_X = BUTTONS_MIN_X + BUTTONS_WIDTH

    BUTTONS_STEP = BUTTON_WIDTH + DISTANCE_BETWEEN_BUTTONS

    RIGHT_PANEL_WIDTH = 8 * CELL_SIZE

    IS_USELESS_DECK_LABEL_MIN_X = \
        DISPLAYED_PART_OF_FIELD_MAX_X + HALF_OF_CELL_SIZE

    IS_USELESS_DECK_LABEL_MIN_Y = DISPLAYED_PART_OF_FIELD_MIN_Y

    IS_USELESS_DECK_LABEL_WIDTH = RIGHT_PANEL_WIDTH

    IS_USELESS_DECK_LABEL_HEIGHT = HALF_OF_CELL_SIZE

    HAS_PLAYER_RIGHT_TO_MOVE_LABEL_MIN_X = \
        IS_USELESS_DECK_LABEL_MIN_X

    HAS_PLAYER_RIGHT_TO_MOVE_LABEL_MIN_Y = \
        DISPLAYED_PART_OF_FIELD_MIN_Y + CELL_SIZE

    HAS_PLAYER_RIGHT_TO_MOVE_LABEL_WIDTH = RIGHT_PANEL_WIDTH

    HAS_PLAYER_RIGHT_TO_MOVE_LABEL_HEIGHT = HALF_OF_CELL_SIZE

    LEADERBOARD_WIDTH = RIGHT_PANEL_WIDTH

    LEADERBOARD_MIN_X = \
        HAS_PLAYER_RIGHT_TO_MOVE_LABEL_MIN_X

    LEADERBOARD_MIN_Y = DISPLAYED_PART_OF_FIELD_MIN_Y + 2 * CELL_SIZE

    LEADERBOARD_ROW_RECT_WIDTH = LEADERBOARD_WIDTH

    LEADERBOARD_ROW_RECT_HEIGHT = HALF_OF_CELL_SIZE

    LEADERBOARD_MAX_SIZE = 5

    PLAYERS_QUEUE_WIDTH = LEADERBOARD_WIDTH

    PLAYERS_QUEUE_MIN_X = LEADERBOARD_MIN_X

    PLAYERS_QUEUE_MIN_Y = \
        (LEADERBOARD_MIN_Y + LEADERBOARD_MAX_SIZE *
         LEADERBOARD_ROW_RECT_HEIGHT)

    PLAYERS_QUEUE_ROW_RECT_WIDTH = LEADERBOARD_ROW_RECT_WIDTH

    PLAYERS_QUEUE_ROW_RECT_HEIGHT = LEADERBOARD_ROW_RECT_HEIGHT

    WIDTH = (DISPLAYED_PART_OF_FIELD_WIDTH +
             2 * HALF_OF_CELL_SIZE) + LEADERBOARD_WIDTH

    HEIGHT = (HALF_OF_CELL_SIZE +
              DISPLAYED_PART_OF_FIELD_HEIGHT +
              LOWER_PANEL_HEIGHT)


# перечисление "константы игры".
class GameConstants:
    BLACK_COLOR = pygame.Color("black")

    WHITE_COLOR = pygame.Color("white")

    BLUE_COLOR = pygame.Color("#1E90FF")

    GREEN_COLOR = pygame.Color("green")

    RED_COLOR = pygame.Color("red")

    PURPLE_COLOR = pygame.Color("purple")

    GOLD_COLOR = pygame.Color("#FFD700")

    GRAY_COLOR = pygame.Color("darkgray")

    SHIFT_OF_DISPLAYED_PART_OF_FIELD_KEYS = (
        pygame.K_w,
        pygame.K_s,
        pygame.K_a,
        pygame.K_d,
        pygame.K_UP,
        pygame.K_DOWN,
        pygame.K_LEFT,
        pygame.K_RIGHT,
        pygame.K_c)

    CHOICE_OF_DECK_CHIP_KEYS = (
        pygame.K_1,
        pygame.K_2,
        pygame.K_3,
        pygame.K_4,
        pygame.K_5,
        pygame.K_6)

    SIMPLE_ACTIONS_KEYS = (
        pygame.K_b,
        pygame.K_m,
        pygame.K_e,
        pygame.K_r,
        pygame.K_f,
        pygame.K_g)
